### ISSUE TITLE
Consider minimal meson.build support

### ISSUE THREAD

**Issue by willwray** [cschreib/snitch#54]
Some low-friction meson support in snitch might aid in its adoption.

meson use is growing in FOSS projects, particularly in the Python world.
I prefer it for personal projects and promote its use in my work
(and work with CMake when I have to).

I've set up a project to use snitch via meson, using its CMake module.
This means that the config step is run with CMake, then meson just
picks up the generated `snitch.hpp` and can make a library target.
It's working so far (I'll get round to testing on Windows eventually).

This is workable but a bit over complicated and feels brittle.

Catch2 has meson support; its top-level [`meson.build`](https://github.com/catchorg/Catch2/blob/devel/meson.build) file is minimal
then the [src](https://github.com/catchorg/Catch2/blob/devel/src/catch2/meson.build) and [test](https://github.com/catchorg/Catch2/blob/devel/tests/meson.build) subdir `meson.build` files are much larger.
I'm no build expert, but this seems heavyweight.

To start with, meson build might just handle single header mode.

I'm up to test and review any support, and might be able to help.
The meson devs are pretty approachable.

What do you think?

**Comment by cschreib** [comment]
Hi and thank you for the suggestion. I don't have anything against adding first class support for other build systems, however I have never used meson and I am not inclined to learn it at the moment.

If you would like to contribute build files for meson, that would be welcome!

Note, currently the `snatch_all.hpp` header is produced using pure CMake; I thought that would allow it to handle dependencies naturally (i.e., rebuild the header each time the source has changed), but that is currently not working. So I would actually prefer now to have an external script to do it (say, python), which could then be called from other build systems and produce the header-only header consistenly. That is the only roadblock I can think of right now.

**Comment by eli-schwartz** [comment]
> Note, currently the `snatch_all.hpp` header is produced using pure CMake; I thought that would allow it to handle dependencies naturally (i.e., rebuild the header each time the source has changed), but that is currently not working. So I would actually prefer now to have an external script to do it (say, python), which could then be called from other build systems and produce the header-only header consistenly. That is the only roadblock I can think of right now.

Doing it in pure cmake means that inherently the ONLY way to re-do it is to re-run cmake. This is generally a bad idea for any buildsystem outputs, except in the case of the proverbial config.h which classically is all about freezing buildsystem introspection probes into a source code accessible format.

I would definitely recommend using an external script.

**Comment by willwray** [comment]
Looking into auto-generating an amalgamated header for a current project
I rediscovered [pcpp](https://github.com/ned14/pcpp) pure Python C preprocessor which does a nice job.

My plan is to generate the header via a github action,
that way Python and pcpp are not project dependencies.

**Comment by willwray** [comment]
@eli-schwartz - do you have thoughts on how to add meson support to snitch?

Given that meson's CMake module works for snitch (or seems to)
then that might argue against adding first class meson support, or,
that meson support should use the CMake module to avoid duplicated effort.

I don't grok the snitch config step yet,
and tend to think of config as implicitly handled by the build system
in the initial cmake call or meson setup.
Maybe the config step can be made more portable.

**Comment by eli-schwartz** [comment]
> Given that meson's CMake module works for snitch (or seems to) then that might argue against adding first class meson support, or, that meson support should use the CMake module to avoid duplicated effort.

First class meson support has an advantage: you don't need *two* build systems installed. As you said, it's brittle.

In fact, Meson hopes the cmake module is useful to people, it's just not guaranteed to work to the same extent. ;)

Also some things only work with meson-based subprojects, not cmake ones. I'm particularly thinking of `dependency('snitch')` automatically invoking the subproject on demand, if it cannot be found via snitch.pc or snitch-config.cmake.

**Comment by cschreib** [comment]
> My plan is to generate the header via a github action, that way Python and pcpp are not project dependencies.

It might be complicated to handle for `snitch`, because some tests use the "amalgamated" header (to test that the header works). So that would have to be done as a pre-configure or pre-buld step before running tests. Then it also means you can't test the amalgamated header locally unless you manually run the script to create the header.

For these reasons, I'd prefer if it was integrated in the build system as a custom command to run.

**Comment by willwray** [comment]
> you can't test the amalgamated header locally unless you manually run the script to create the header

That seems acceptable to me.
I see generating the header as a 'developer' thing, and this would be a pre-CI check;
developers would have to install pcpp to generate and test locally in my setup, and that's ok
(after all, with meson, Python is already an implicit dependency so pcpp is a simple install).
Then CI will regenerate the header anyway, and hopefully fail CI checks if there is a problem.
Mostly, the amalgamated header should work as long as the component headers test out.

Users or packagers just pick up the provided pre-tested amalgamated header.
They don't need to regenerate (right?).
If users want to edit headers and then amalgamate ...
then I'd question if they _should_ be using an amalgamated header;
"just set up a build, already, and do it right".

For test frameworks like snitch a single-header solution is enticing, to avoid deeper dependency.

For me, the amalgamated header is something to provide a quick-start evaluation,
to `#include` via url on Compiler Explorer so all code is fully manifest for inspection and play.
I don't want to encourage dependence on a single header out of dev laziness
(or build system apprehension).

Then again, my libs are usually header-only metaprogramming things
so there's no real need for a build system - they're naturally header only.
I wouldn't want to actively discourage straightforward single-header usage.

**Comment by willwray** [comment]
So many dilemmas here, it's almost funny.
I've bred a few more for my project too!
I know that minimality is an aim for snitch,
and a reason for my gravitating towards it.
Guess we'll all learn something from this,
and you might end up with an apology...

**Comment by cschreib-ibex** [comment]
> > you can't test the amalgamated header locally unless you manually run the script to create the header
> 
> That seems acceptable to me. I see generating the header as a 'developer' thing, and this would be a pre-CI check; developers would have to install pcpp to generate and test locally in my setup, and that's ok (after all, with meson, Python is already an implicit dependency so pcpp is a simple install). Then CI will regenerate the header anyway, and hopefully fail CI checks if there is a problem. Mostly, the amalgamated header should work as long as the component headers test out.

Currently the amalgamated header is only re-generated if it is missing, so I have to manually delete it for it to re-build whenever I want to run tests while developing. In a sense, it's the same as what you propose, i.e., the developer needs some manual intervention to re-build the header when needed. I found this to be a sizeable pain in the bum, especially since the build system has all the info it needs to figure out if the header should be re-built or not, so it should be easy to get it to work automatically.

> Users or packagers just pick up the provided pre-tested amalgamated header.
They don't need to regenerate (right?).

You're right, it's only for developers of the library. End users can just grab the header from the tagged release, or wherever that gets uploaded.

**Comment by eli-schwartz** [comment]
autotools has a fancy trick for declaring generated sources that only get regenerated if their inputs are out of date. ;)

It might be worth implementing in meson, I've thought about it before... Basically, you have a target that depends on the inputs, but is wrapped to handle out of source build directories by checking if the generated source is available in the source tree, and just uses that instead. The build program isn't reported as missing unless you actually need to rebuild the sources.

For this project you could just require python, and have a python script that figures out if the generated header is already up to date and just copies that to the build directory, *or* attempts to actually run pcpp. If the user doesn't have pcpp installed, that probably doesn't matter as the script can just copy the pre-distributed version. If the header is actually modified, suddenly it has to get rebuilt, and the script emits an error message "failed to generate foo.h, because pcpp is not installed".

**Comment by cschreib** [comment]
As of https://github.com/cschreib/snitch/pull/55, the creation of the "amalgamated" header is done in Python, so this should make it easier to use from another build system. I won't go further than this myself :)

**Comment by willwray** [comment]
I've prepared a patch for meson.build support. It almost works...

The patch attempts to duplicate snitch's CMake configure_file set up.
However, meson cannot yet substitute `# cmakedefine01` lines in `snitch_config.hpp.config`.
There's a meson PR to fix the missing feature https://github.com/mesonbuild/meson/pull/11328.
Once the meson PR is merged and tested I'll open a PR here to review the patch.

Unfortunately, this will require latest meson - that'll put off some potential mesonites.

**Comment by cschreib** [comment]
Thank you! Is there something we can change to the config file to make it nicer on meson and not require the very latest version?

**Comment by willwray** [comment]
It's just the `# cmakedefine01` BOOL ON/OFF config variables that are unsupported
https://cmake.org/cmake/help/latest/command/configure_file.html

meson does support plain `# cmakedefine` for BOOL ON/OFF variables.

So I can see two options for immediate support:

1. change to plain `cmakedefine` and change tests from `#if VAR` to `#ifdef VAR`  
or the more refined  `#if defined(VAR)`
2. change to regular CMake variable expansion `${VAR}` as for the other, numerical, config parameters (and changing ON/OFF settings to 1/0  I guess)
```
#if !defined(SNITCH_DEFINE_MAIN)
# define SNITCH_DEFINE_MAIN ${SNITCH_DEFINE_MAIN}
```
then this expands, for an ON setting changed to 1:
```
#if !defined(SNITCH_DEFINE_MAIN)
# define SNITCH_DEFINE_MAIN 1
```
(i.e. the same expansion as the current BOOL variables, so the tests can stay the same)

**Comment by eli-schwartz** [comment]
Meson effectively "supports" this as though it were a regular cmakedefine, so passing it a 0/1 from Meson will still do the correct thing. No Meson changes are needed.

**Comment by willwray** [comment]
The `# cmakedefine01` issue is actually just the whitespace between `#` and `cmakedefine01`.
Editing to `#cmakedefine01` the substitution is done correctly.
I'll include that in the patch, then test locally before pushing a PR when it's ready for review.

**Comment by willwray** [comment]
PR #71, forgot to link this issue.

@eli-schwartz : please take a look, and don't hold back
