### ISSUE TITLE
Suspicious static_assert condition in get_format_code()

### ISSUE THREAD

**Issue by tocic** [cschreib/snitch#66]
https://github.com/cschreib/snitch/blob/eaa322ce9e7bbfbd0b39aa529ea59de4acbd9c42/src/snitch.cpp#L61-L64

I think `static_assert(not std::is_same_v<T, T>, "unsupported type");` was implied. Now it leads to [UB](https://timsong-cpp.github.io/cppwp/n4861/stmt.return#2).

**Comment by cschreib** [comment]
Good catch!
